/**
 * Work Tickets Service — Sprint 45B
 * ====================================
 * DIRECT Supabase client for EVERYTHING. No PowerSync for signature operations
 * (PowerSync sync delay breaks signing flows — battle-tested rule from
 * Jantile Tracker). For work ticket CRUD, direct Supabase also ensures the
 * SERIAL `number` is returned immediately by the server-side trigger.
 *
 * Types mirror Takeoff Web exactly. Storage path for signatures:
 *   signatures/{organization_id}/{token}.png
 */

import { Platform } from 'react-native';
import * as Crypto from 'expo-crypto';
import { supabase } from '@/shared/lib/supabase/client';
import { SIGN_BASE_URL } from '@/shared/config/urls';
import type {
  WorkTicket,
  WorkTicketDraft,
  WorkTicketStatus,
  DocumentSignature,
  SignerRole,
  LaborEntry,
  MaterialEntry,
} from '../types';

// ─── Read ─────────────────────────────────────────────────────

export interface WorkTicketWithSignature extends WorkTicket {
  sig_status?: DocumentSignature['status'] | null;
  sig_signer_name?: string | null;
  sig_signed_at?: string | null;
}

export async function listWorkTickets(projectId: string): Promise<WorkTicketWithSignature[]> {
  const [ticketsRes, sigsRes] = await Promise.all([
    supabase
      .from('work_tickets')
      .select('*')
      .eq('project_id', projectId)
      .order('created_at', { ascending: false }),
    supabase
      .from('document_signatures')
      .select('*')
      .eq('document_type', 'work_ticket')
      .eq('project_id', projectId),
  ]);

  if (ticketsRes.error) throw ticketsRes.error;
  const tickets = (ticketsRes.data ?? []) as WorkTicket[];
  const sigs = (sigsRes.data ?? []) as DocumentSignature[];

  const latestByDoc = new Map<string, DocumentSignature>();
  for (const sig of sigs) {
    const prev = latestByDoc.get(sig.document_id);
    if (!prev || sig.created_at > prev.created_at) latestByDoc.set(sig.document_id, sig);
  }

  return tickets.map((t) => {
    const sig = latestByDoc.get(t.id);
    return {
      ...t,
      sig_status: sig?.status ?? null,
      sig_signer_name: sig?.signer_name ?? null,
      sig_signed_at: sig?.signed_at ?? null,
    };
  });
}

export async function getWorkTicket(id: string): Promise<WorkTicket | null> {
  const { data, error } = await supabase
    .from('work_tickets')
    .select('*')
    .eq('id', id)
    .maybeSingle();
  if (error) throw error;
  return (data as WorkTicket | null) ?? null;
}

export async function getSignatureForTicket(
  ticketId: string,
): Promise<DocumentSignature | null> {
  const { data, error } = await supabase
    .from('document_signatures')
    .select('*')
    .eq('document_type', 'work_ticket')
    .eq('document_id', ticketId)
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle();
  if (error) throw error;
  return (data as DocumentSignature | null) ?? null;
}

// ─── Write ────────────────────────────────────────────────────

export interface CreateTicketInput extends WorkTicketDraft {}

export async function createWorkTicket(input: CreateTicketInput): Promise<WorkTicket> {
  // title is NOT NULL in DB — auto-generate from trade + area_description
  const autoTitle = [input.trade, input.area_description].filter(Boolean).join(' — ') || 'Work Ticket';

  const { data, error } = await supabase
    .from('work_tickets')
    .insert({
      organization_id: input.organization_id,
      project_id: input.project_id,
      title: autoTitle,
      area: input.area_description,           // legacy column kept in DB
      service_date: input.service_date,
      trade: input.trade,
      area_description: input.area_description,
      floor: input.floor,
      foreman_name: input.foreman_name,
      priority: input.priority,
      work_description: input.work_description,
      labor: input.labor,
      materials: input.materials,
      gc_notes: input.gc_notes,
      status: 'draft' as WorkTicketStatus,
      created_by: input.created_by,
    })
    .select()
    .single();
  if (error) throw error;
  return data as WorkTicket;
}

export async function updateWorkTicket(
  id: string,
  patch: Partial<WorkTicketDraft> & { status?: WorkTicketStatus },
): Promise<WorkTicket> {
  const { data, error } = await supabase
    .from('work_tickets')
    .update({
      ...patch,
      updated_at: new Date().toISOString(),
    })
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;
  return data as WorkTicket;
}

export async function deleteWorkTicketDraft(id: string): Promise<void> {
  // Safety: only drafts can be deleted.
  const { error } = await supabase
    .from('work_tickets')
    .delete()
    .eq('id', id)
    .eq('status', 'draft');
  if (error) throw error;
}

// ─── Signatures ───────────────────────────────────────────────

/**
 * Create a pending signature request. Used by BOTH in-app signing and link share.
 * - Inserts a `document_signatures` row (status=pending, token auto-generated by DB default if set, else provide)
 * - Flips the parent ticket to status='pending'
 */
export async function createSignatureRequest(params: {
  ticketId: string;
  organization_id: string;
  project_id: string;
  signer_name?: string;      // optional — GC can enter on sign page
  signer_role: SignerRole;
}): Promise<DocumentSignature> {
  const { data, error } = await supabase
    .from('document_signatures')
    .insert({
      document_type: 'work_ticket',
      document_id: params.ticketId,
      organization_id: params.organization_id,
      project_id: params.project_id,
      signer_name: params.signer_name ?? 'Pending',
      signer_role: params.signer_role,
      status: 'pending',
    })
    .select()
    .single();
  if (error) throw error;

  // Flip ticket to pending
  await supabase
    .from('work_tickets')
    .update({ status: 'pending' })
    .eq('id', params.ticketId);

  return data as DocumentSignature;
}

/**
 * Cancel a pending signature — marks the latest pending signature as 'declined'
 * (so its token can't be used) and reverts the ticket to draft.
 */
export async function cancelSignatureRequest(ticketId: string): Promise<void> {
  const sig = await getSignatureForTicket(ticketId);
  if (sig && sig.status === 'pending') {
    await supabase
      .from('document_signatures')
      .update({ status: 'declined' })
      .eq('id', sig.id);
  }
  await supabase
    .from('work_tickets')
    .update({ status: 'draft' })
    .eq('id', ticketId);
}

/**
 * In-app signing flow: the GC physically signs on the foreman's device.
 * Uploads the signature PNG to the `signatures` bucket at
 * `{organization_id}/{token}.png`, computes SHA-256 integrity hash, updates
 * `document_signatures` and parent `work_tickets`.
 *
 * Upload errors are caught and thrown (no silent failures — lesson from
 * FIXES_WORK_TICKET_SIGNATURES.md).
 */
export async function signTicketInApp(params: {
  signatureId: string;
  token: string;
  organizationId: string;
  signerName: string;
  signerTitle?: string;
  signatureDataUrl: string; // "data:image/png;base64,..." from signature pad
  gcNotes?: string;
}): Promise<void> {
  const {
    signatureId,
    token,
    organizationId,
    signerName,
    signerTitle,
    signatureDataUrl,
    gcNotes,
  } = params;

  // 1) Decode base64 → bytes
  const base64 = signatureDataUrl.replace(/^data:image\/png;base64,/, '');
  const bytes = base64ToBytes(base64);

  // 2) Upload to signatures bucket at the shared convention path.
  //    MUST match Takeoff Web: signatures/{org_id}/{token}.png
  const filePath = `${organizationId}/${token}.png`;
  const { error: uploadErr } = await supabase.storage
    .from('signatures')
    .upload(filePath, bytes, {
      contentType: 'image/png',
      upsert: true,
    });

  if (uploadErr) {
    // NEVER swallow upload errors — this is the bug from FIXES_WORK_TICKET_SIGNATURES.md
    throw new Error(`Signature upload failed: ${uploadErr.message}`);
  }

  // 3) Public URL
  const { data: urlData } = supabase.storage.from('signatures').getPublicUrl(filePath);
  const publicUrl = urlData.publicUrl;

  // 4) SHA-256 integrity hash — includes sorted photo URLs for
  //    deterministic hashing across Track and Takeoff Web.
  const signedAt = new Date().toISOString();

  // Resolve ticket ID from signature, then fetch evidence_photos for hash
  const { data: sigDoc } = await supabase
    .from('document_signatures')
    .select('document_id')
    .eq('id', signatureId)
    .single();
  let photoUrls = '';
  if (sigDoc) {
    const { data: tkt } = await supabase
      .from('work_tickets')
      .select('evidence_photos')
      .eq('id', sigDoc.document_id)
      .single();
    if (tkt?.evidence_photos) {
      const photos: { url?: string; pending_upload?: boolean }[] =
        Array.isArray(tkt.evidence_photos) ? tkt.evidence_photos : [];
      photoUrls = photos
        .filter((p) => !p.pending_upload && p.url)
        .map((p) => p.url!)
        .sort()
        .join('|');
    }
  }

  const payload = JSON.stringify({
    signatureId,
    signerName,
    signerTitle: signerTitle ?? '',
    signedAt,
  }) + (photoUrls ? `|photos:${photoUrls}` : '');
  const contentHash = await Crypto.digestStringAsync(
    Crypto.CryptoDigestAlgorithm.SHA256,
    payload,
  );

  // 5) Update document_signatures → signed
  const fullSignerName = signerTitle ? `${signerName} — ${signerTitle}` : signerName;
  const { error: sigErr } = await supabase
    .from('document_signatures')
    .update({
      status: 'signed',
      signature_url: publicUrl,
      signed_at: signedAt,
      signer_name: fullSignerName,
      content_hash: contentHash,
      hash_algorithm: 'SHA-256',
      hashed_at: signedAt,
      ip_address: null,
      user_agent: `NotchField Track (${Platform.OS})`,
    })
    .eq('id', signatureId);
  if (sigErr) throw sigErr;

  // 6) Update parent ticket → signed (+ gc_notes if provided)
  const { data: sigRow } = await supabase
    .from('document_signatures')
    .select('document_id')
    .eq('id', signatureId)
    .single();

  if (sigRow) {
    const ticketUpdate: Record<string, unknown> = { status: 'signed' };
    if (gcNotes) ticketUpdate.gc_notes = gcNotes;
    await supabase
      .from('work_tickets')
      .update(ticketUpdate)
      .eq('id', (sigRow as { document_id: string }).document_id);
  }
}

/**
 * Compose the public signing URL for link-share mode.
 */
export function getSigningUrl(token: string): string {
  return `${SIGN_BASE_URL}/${token}`;
}

// ─── Helpers ───────────────────────────────────────────────────

function base64ToBytes(base64: string): Uint8Array {
  // React Native supports atob via Hermes polyfill in recent Expo SDKs.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const atobFn: (s: string) => string = (globalThis as any).atob ?? fallbackAtob;
  const binary = atobFn(base64);
  const len = binary.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function fallbackAtob(input: string): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';
  let str = input.replace(/=+$/, '');
  let output = '';
  if (str.length % 4 === 1) throw new Error('Invalid base64');
  for (
    let bc = 0, bs = 0, buffer, i = 0;
    (buffer = str.charAt(i++));
    ~buffer && ((bs = bc % 4 ? bs * 64 + buffer : buffer), bc++ % 4)
      ? (output += String.fromCharCode(255 & (bs >> ((-2 * bc) & 6))))
      : 0
  ) {
    buffer = chars.indexOf(buffer);
  }
  return output;
}

// ─── JSON helpers (for UI consuming jsonb columns) ─────────────
// Supabase returns jsonb as native objects/arrays already, so these are
// mostly identity helpers with safe fallbacks in case of bad data.

export function ensureLabor(val: unknown): LaborEntry[] {
  return Array.isArray(val) ? (val as LaborEntry[]) : [];
}

export function ensureMaterials(val: unknown): MaterialEntry[] {
  return Array.isArray(val) ? (val as MaterialEntry[]) : [];
}
