/**
 * Sprint 53A — Messages feature types.
 *
 * The DB CHECK constraint on field_messages.message_type is exactly:
 *   message_type IN ('info', 'blocker', 'safety', 'question')
 * Verified against information_schema 2026-04-24. Confirmed by Takeoff Web team.
 * Don't expand this enum unilaterally — it's a contract with downstream Web UI.
 */

import { z } from 'zod';

export const MESSAGE_TYPES = ['info', 'blocker', 'safety', 'question'] as const;
export type MessageType = (typeof MESSAGE_TYPES)[number];

export const MessageTypeSchema = z.enum(MESSAGE_TYPES);

export const FieldMessageSchema = z.object({
  id: z.string().uuid(),
  organization_id: z.string().uuid(),
  project_id: z.string().uuid(),
  area_id: z.string().uuid().nullable(),
  sender_id: z.string().uuid(),
  message_type: MessageTypeSchema,
  message: z.string().min(1),
  photos: z.array(z.string()).default([]),
  created_at: z.string(),
  // Joined / display fields — computed in service, not in DB row
  sender_name: z.string().nullable().optional(),
  sender_role: z.string().nullable().optional(),
  area_label: z.string().nullable().optional(),
  // Track-internal flag — NOT persisted to DB. True when this message was
  // auto-generated by blockPhase, signed_off, or any system action. We detect
  // this client-side by regex on message body (structured prefix). See
  // SystemMessagePrefix below.
  is_system: z.boolean().optional(),
});

export type FieldMessage = z.infer<typeof FieldMessageSchema>;

/**
 * Auto messages from blockPhase / system actions use this prefix in the body.
 * The prefix is stripped for display; the badge is rendered separately.
 *
 * Format: `[SYS:{kind}] {body}`
 * Example: `[SYS:blocker] Phase "Tile Install" blocked — reason: other_trade`
 *
 * Web team agreed not to filter these out (they appear in the feed) but we
 * tag them with `is_system: true` for visual distinction (lock icon).
 */
export const SystemMessagePrefix = /^\[SYS:([^\]]+)\]\s*/;

export function isSystemMessage(body: string): boolean {
  return SystemMessagePrefix.test(body);
}

export function stripSystemPrefix(body: string): string {
  return body.replace(SystemMessagePrefix, '');
}

/**
 * Display config per message type — colors + icon.
 * Used by MessageTypeBadge + MessageBubble border accent.
 */
export const MESSAGE_TYPE_CONFIG: Record<
  MessageType,
  { label: string; icon: string; color: string; bgColor: string }
> = {
  info:     { label: 'Note',     icon: 'chatbubble-outline',     color: '#94A3B8', bgColor: '#94A3B820' },
  blocker:  { label: 'Blocker',  icon: 'lock-closed',            color: '#EF4444', bgColor: '#EF444420' },
  safety:   { label: 'Safety',   icon: 'shield-checkmark',       color: '#F59E0B', bgColor: '#F59E0B20' },
  question: { label: 'Question', icon: 'help-circle-outline',    color: '#3B82F6', bgColor: '#3B82F620' },
};
